src/java/webcasemngmtsystem/LoginBean.java
package webcasemngmtsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author Tommy
 */
@ManagedBean
@RequestScoped
public class LoginBean {

    private String username;
    private String password;
    private String errorLoginMessage2 = "";

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return this.username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return this.password;
    }

    public String tryLogin() {
        Connection con = null;
        Statement stmt = null;
        try {
            con = DBConnector.getConnection();
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from users where username = '"
                    + username + "' and password = '" + password + "'");
            if (rs.next()) {
                if (rs.getString("role").equals("Technician")) {
                    User.setUser(rs);
                    return "main";
                } else
                    setErrorLoginMessage2("You are not a valid user");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
            }
        }
        return "index";
    }

    public String getErrorLoginMessage() {
        if (username != null && password != null) {
            return "User: " + username + " with password: " + password
                    + " was not found";
        } else {
            return "";
        }
    }

    public void setErrorLoginMessage2(String msg) {
        this.errorLoginMessage2 = msg;
    }
    public String getErrorLoginMessage2() {
        return this.errorLoginMessage2;
    }
}

src/java/webcasemngmtsystem/ManageCaseBean.java
/*
 * Här laddas ett case vid knapptryck(Edit)
 * och när man registrerar ett nytt case
 * Dessa cases kommer också att sparas här
 */
package webcasemngmtsystem;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Tommy och Robin
 */
@ManagedBean
@SessionScoped
public class ManageCaseBean {

    Connection con = null;
    Statement stmt = null;
    private Case caseToEdit;

    public Case getCaseToEdit() {
        return this.caseToEdit;
    }

    public int getCaseId() {
        return caseToEdit.getId();
    }

    public String getDepartment() {
        return caseToEdit.getDepartment();
    }

    public String getTotalCost() {
        return caseToEdit.getTotalCost();
    }

    public String getTotalHours() {
        return caseToEdit.getTotalHours();
    }

    public String getDescription() {
        return caseToEdit.getDescription();
    }

    public void setDescription(String description) {
        caseToEdit.setDescription(description);
    }

    public String getActualCost() {
        return caseToEdit.getActualCost();
    }

    public void setActualCost(String actualCost) {
        caseToEdit.setActualCost(actualCost);
    }

    public String getActualHours() {
        return caseToEdit.getActualHours();
    }

    public void setActualHours(String actualHours) {
        caseToEdit.setActualHours(actualHours);
    }

    public String edit(Case caseToEdit) {
        this.caseToEdit = caseToEdit;
        return "statetimeandcost";
    }

    public String newCase() {
        this.caseToEdit = new Case();
        return "addcase";
    }

    public String saveCase() {
        String query;
        if (caseToEdit.getId() < 1) {
            //System.out.println("Spara nytt case här: " + caseToEdit.getDescription());
            String sqlValues = "('" + User.department + "','" + caseToEdit.getDescription()
                    + "','" + User.username + "',1)";
            query = "INSERT INTO cases (department,description,author,stage) VALUES " + sqlValues;
        } else {
            //As of now we have costs and hours saved as string in the 
            //database so we have to parse them to Integers
            int totCost = Integer.parseInt(caseToEdit.getTotalCost());
            int totHours = Integer.parseInt(caseToEdit.getTotalHours());
            int actCost = Integer.parseInt(caseToEdit.getActualCost());
            int actHours = Integer.parseInt(caseToEdit.getActualHours());
            if (actCost <= totCost && actHours <= totHours) {
                caseToEdit.setStage(4);
            } else {
                caseToEdit.setStage(3);
            }
            query = "UPDATE cases SET actualcost='" + caseToEdit.getActualCost() + "', actualhours='"
                    + caseToEdit.getActualHours() + "', stage=" + caseToEdit.getStage() + " WHERE id=" + caseToEdit.getId();
        }
        try {
            con = DBConnector.getConnection();
            stmt = con.createStatement();
            stmt.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCaseBean.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
            }
        }
        return "main";
    }

    // This method is not used any more
    public String getTemporaryString() {
        return "<p style=\"background-color:green;width:150px;\">Stage: " + caseToEdit.getStage() + "</p>";
    }
}

src/java/webcasemngmtsystem/ManageCasesBean.java
/*
 * This bean are supposed to handle everything that has
 * to do with a users cases, get cases.
 */
package webcasemngmtsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.sql.rowset.CachedRowSet;

/**
 *
 * @author Tommy och Robin
 */
@ManagedBean
@SessionScoped
public class ManageCasesBean {

    Connection con = null;
    Statement stmt = null;
    private List<Case> cases;
    private int caseId;
    private Case caseToEdit;
    //Variables reguired for saving a new case by a technician
    private String description;
    
    public Case getCaseToEdit() {
        return this.caseToEdit;
    }
    public int getCaseId() {
        return this.caseId;
    }
    
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    public String getUserFullName() {
        return User.fullName;
    }

    public String getUserDepartment() {
        return User.department;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    /*
    public ResultSet getCases() {
        try {
            con = DBConnector.getConnection();
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from cases where assignedTechnician = '"
                    + User.fullName + "' and stage = 2");
            CachedRowSet rowSet = new com.sun.rowset.CachedRowSetImpl();
            rowSet.populate(rs);
            return rowSet;
        } catch (SQLException ex) {
            Logger.getLogger(ManageCasesBean.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
            }
        }
        return null;
    }
    */

    public List<Case> getCases2() {
        Case oneCase;
        cases = new ArrayList<Case>();
        try {
            con = DBConnector.getConnection();
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from cases where assignedTechnician = '"
                    + User.fullName + "' and stage = 2");
            while(rs.next()) {
                oneCase = new Case(rs.getInt("id"),rs.getString("description"),rs.getString("department"),
                        rs.getString("totalcost"),rs.getString("totalhours"),rs.getString("actualcost"),
                        rs.getString("actualhours"),rs.getInt("stage"));
                cases.add(oneCase);
            }
            return cases;
        } catch (SQLException ex) {
            Logger.getLogger(ManageCasesBean.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
            }
        }
        return null;
    }

    //This is not used anymore
    /*
    public String save() {
        String sqlValues = "('" + User.department + "','" + getDescription()
                + "','" + User.username + "',1)";
        String query = "INSERT INTO cases (department,description,author,stage) VALUES " + sqlValues;
        try {
            con = DBConnector.getConnection();
            stmt = con.createStatement();
            stmt.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCasesBean.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
            }
        }
        return "main";
    }
    */

    //This is not used anymore
    /*
    public String edit(Case caseToEdit) {
        this.caseToEdit = caseToEdit;
        return "statetimeandcost";
    }
    
    public String getDesc() {
        return caseToEdit.getDescription();
    }
    */
}

web/addcase.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Web Case Management System: Add new case</title>
        <h:outputStylesheet name="style.css" library="css"/>
    </h:head>
    <h:body>
        <h1>Register a new case</h1>
        <p>
            Please fill out the form to register a new <br></br>
            case at your department: #{manageCasesBean.userDepartment}
        </p>
        <h:form>
            <h:panelGrid columns="3">
                <h:outputText value="Description:"/>
                <h:inputTextarea cols="30" rows="10" id="descriptionInputText" required="true"
                                 requiredMessage="Please enter a description"
                                 value="#{manageCaseBean.description}"
                             validatorMessage="You can only use a maximum of 100 chars">
                    <f:validateLength maximum="100"/>
                </h:inputTextarea>
                <h:message for="descriptionInputText" styleClass="error"/>
            </h:panelGrid>
            <h:commandButton value="Save case" action="#{manageCaseBean.saveCase}"/>
        </h:form>
        <div><h:outputLink value="main.xhtml">
                Return to main page
            </h:outputLink>
        </div>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Web Case Management System</title>
        <h:outputStylesheet name="style.css" library="css"/>
    </h:head>
    <h:body>
        <h:form>
            <h1>Welcome to FejkAB:s Web Case Management System</h1>
            <p>Please enter username and password to login</p>
            <h:panelGrid columns="3">
                <h:outputText value="Username:"/>
                <h:inputText id="userNameInput" required="true"
                             requiredMessage="Forgot to enter username?"
                             value="#{loginBean.username}"/>
                <h:message for="userNameInput" styleClass="error"/>
                <h:outputText value="Password:"/>
                <h:inputSecret id="passWordInput" required="true"
                             requiredMessage="Forgot to enter password?"
                             value="#{loginBean.password}"/>
                <h:message for="passWordInput" styleClass="error"/>
            </h:panelGrid>
            <h:commandButton value="Login" action="#{loginBean.tryLogin}"/>
        </h:form>
        <p><h:outputText escape="false" value="#{loginBean.errorLoginMessage}" styleClass="error"/></p>
        <h:outputText escape="false" value="#{loginBean.errorLoginMessage2}" styleClass="error"/>
    </h:body>
</html>

web/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Web Case Management System: Main page</title>
        <h:outputStylesheet name="style.css" library="css"/>
    </h:head>
    <h:body>
        <h1>Welcome #{manageCasesBean.userFullName}</h1>
        <p>Theese cases has been assigned to you:</p>
        <h:form>
            <h:dataTable value="#{manageCasesBean.cases2}" var="case"
                         rowClasses="oddRows,evenRows" headerClass="header"
                         styleClass="table" cellpadding="5" cellspacing="0">
                <h:column>
                    <f:facet name="header">Id</f:facet>
                        #{case.id}
                </h:column>
                <h:column>
                    <f:facet name="header">Description</f:facet>
                        #{case.description}
                </h:column>
                <h:column>
                    <f:facet name="header">Estimated cost</f:facet>
                        #{case.totalCost}
                </h:column>
                <h:column>
                    <f:facet name="header">Estimated hours</f:facet>
                    <h:inputText value="#{case.totalHours}" rendered="#{case.editable}"/>
                    <h:outputText value="#{case.totalHours}" rendered="#{not case.editable}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Actual cost</f:facet>
                        #{case.actualCost}
                </h:column>
                <h:column>
                    <f:facet name="header">Actual hours</f:facet>
                        #{case.actualHours}
                </h:column>
                <h:column>
                    <f:facet name="header">Edit</f:facet>
                    <h:selectBooleanCheckbox value="#{case.editable}" onclick="document.location.reload(true)"/>
                </h:column>
                <h:column>
                    <f:facet name="header">State time and cost</f:facet>
                    <h:commandButton value="Edit" action="#{manageCaseBean.edit(case)}">
                        
                    </h:commandButton>
                </h:column>
            </h:dataTable>
        </h:form>
        <h:form>
            <p><h:commandButton value="Register new case" action="#{manageCaseBean.newCase}"/></p>
            <p><h:commandButton value="Log out" action="index"/></p>
        </h:form>
    </h:body>
</html>

web/statetimeandcost.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>State time and cost</title>
        <h:outputStylesheet name="style.css" library="css"/>
    </h:head>
    <h:body>
        <h1>State time and costs</h1>
        <p>Please enter your costs and time for this case</p>

        <h:panelGrid columns="2">
            <h:outputText value="Case id:"/>
            <h:outputText value="#{manageCaseBean.caseId}"/>
            <h:outputText value="Description:"/>
            <h:outputText value="#{manageCaseBean.description}"/>
            <h:outputText value="Estimated cost:"/>
            <h:outputText value="#{manageCaseBean.totalCost}"/>
            <h:outputText value="Estimated hours:"/>
            <h:outputText value="#{manageCaseBean.totalHours}"/>
        </h:panelGrid>
        <h:form>
            <h:panelGrid columns="3">
                <h:outputText value="Your actual costs:"/>
                <h:inputText id="actualCostInput" required="true"
                             requiredMessage="Please enter your costs"
                             value="#{manageCaseBean.actualCost}"
                             validatorMessage="Input has to be a number between 0 and 99999">
                    <f:validateLongRange minimum="0" maximum="99999"/>
                </h:inputText>
                <h:message for="actualCostInput" styleClass="error"/>
                <h:outputText value="Your actual hours:"/>
                <h:inputText id="actualHoursInput" required="true"
                             requiredMessage="Please enter your hours"
                             value="#{manageCaseBean.actualHours}"
                             validatorMessage="Input has to be a number between 0 and 1000">
                    <f:validateLongRange minimum="0" maximum="1000"/>
                </h:inputText>
                <h:message for="actualHoursInput" styleClass="error"/>
            </h:panelGrid>
            <h:commandButton value="Save" action="#{manageCaseBean.saveCase}"/> 
        </h:form>
        <div><h:outputLink value="main.xhtml">
                Return to main page
            </h:outputLink>
        </div>
    </h:body>
</html>